services:
  - type: web
    name: lamdi-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: MONGO_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
