name: Build Debug APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        # This now points to the correct folder
        run: chmod +x gradlew
        working-directory: frontend/android

      - name: Build APK
        # This runs the build inside the android folder
        run: ./gradlew assembleDebug
        working-directory: frontend/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          # We tell it to search specifically in that folder for the result
          path: frontend/android/app/build/outputs/apk/debug/*.apk
